import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ottercoDisplay = localFont({
	src: [
		{
			path: "../public/fonts/Otterco-Display-Regular.woff2",
			weight: "400",
		},
		{
			path: "../public/fonts/Otterco-Display-Medium.woff2",
			weight: "500",
		},
		{
			path: "../public/fonts/Otterco-Display-SemiBold.woff2",
			weight: "600",
		},
	],
	variable: "--font-otterco-display",
});

const otterco = localFont({
	src: [
		{
			path: "../public/fonts/Otterco-Medium.woff2",
			weight: "500",
		},
	],
	variable: "--font-otterco",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${otterco.variable} ${ottercoDisplay.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
